# Generated by Django 4.2.7 on 2023-11-16 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('cname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=40)),
                ('mobile', models.IntegerField()),
                ('marks1', models.IntegerField()),
                ('marks2', models.IntegerField()),
                ('marks3', models.IntegerField()),
            ],
        ),
    ]
