# Generated by Django 4.2.7 on 2023-11-18 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thrill', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='feed',
            new_name='customer_data',
        ),
    ]
