# Generated by Django 4.2.7 on 2023-11-19 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thrill', '0002_rename_feed_customer_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer_data',
            old_name='Name',
            new_name='name',
        ),
    ]
