# Generated by Django 4.2.7 on 2023-12-02 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thrill', '0005_uploadedimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUploadForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='img/%y')),
            ],
        ),
        migrations.DeleteModel(
            name='UploadedImage',
        ),
    ]
