# Generated by Django 4.2.7 on 2023-12-05 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thrill', '0006_imageuploadform_delete_uploadedimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=50)),
                ('upload_image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.DeleteModel(
            name='ImageUploadForm',
        ),
    ]
