# Generated by Django 4.2.7 on 2023-11-11 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stdinfo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentForm',
            new_name='StudentData',
        ),
    ]
